version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  test:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/node:lts
    working_directory: "~/apps/web"
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: yarn
      - run:
        command: yarn build