version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              only: web
jobs:
  test:
    docker:
      - image: cimg/node:lts
    working_directory: ~/turbo-demo/apps/web
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: yarn
      - run:
        command: yarn build
      - run:
        command: yarn test